name: GitHub Actions Demo
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker
        run: |
          apt install -y docker docker-compose
      - name: Build repo
        run: |
          docker-compose build
      - run: echo "This job's status is ${{ job.status }}."
